### ISSUE TITLE
 Images are not clickable on the cart page. 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Paradise-Store-Dev#13]
**Actual result:**
The images are not clickable in the cart page,
![image](https://user-images.githubusercontent.com/102131636/161255491-abc064f8-8779-4136-9f52-e0287daeb885.png)

**Expected result:**
When we click on the image then it should open the product page.

**Comment by devSharibAli** [comment]
fixed

**Comment by sudhanshu0603** [comment]
ok, resolved
