### ISSUE TITLE
Slider for thmbnails images when the thumbnail image will increase

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Paradise-Store-Dev#19]
**Actual result:** 
When we have many images for thumbnail then slider we can add. (suggestion )
**EXpected result:** 
When we have many images for thumbnail then slider we can add. (suggestion )

**Comment by devSharibAli** [comment]
![image](https://user-images.githubusercontent.com/100212678/161396344-38fd5631-f487-4e5a-b34f-c411b00a9ffc.png)
slider is already there will get added when 4 or more images will be there

**Comment by sudhanshu0603** [comment]
ok , resolved
