### ISSUE TITLE
mobile view header can be reduced more ,it is taking much space

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Paradise-Store-Dev#23]
**Actual result:** 
The header is taking much height, it can eb reduced more.
![image](https://user-images.githubusercontent.com/102131636/161483054-51500bd6-0059-4b37-986f-fd9c87e5930c.png)

**Expected result:** 
The header height can be reduced more it is taking much height.

**Comment by ui-mohdsameerkhan** [comment]
fixed
 @sudhanshu0603

**Comment by sudhanshu0603** [comment]
ok, resolved.
